name 'package-replace'
maintainer 'Inviqa UK LTD'
maintainer_email 'kevans@inviqa.com'
license 'apachev2'
description 'Installs/Configures package-replace'
long_description 'Installs/Configures package-replace'
version '0.1.0'
